# Assignment 3 
# Mustafa Mandor

## 1 

In [1]:
import numpy as np

In [23]:
a=np.array([1,5,0,0,0,2,3])
b=[]
c=0
for i in a:
    if i!=0:
        b.append(i)
    else:
        c+=1
if len(b)!=len(a):
    print("The Array",a,"Contains Zero Elements =",c)

The Array [1 5 0 0 0 2 3] Contains Zero Elements = 3


## 2

In [10]:
import numpy as np

In [25]:
a=np.array([1,5,0,0,0,2,3])
b=[]
c=0
for i in a:
    if i==0:
        b.append(i)
    else:
        c+=1
if len(b)!=len(a):
    print("The Array:",a,"Contains Non-Zero Elements =",c)


The Array: [1 5 0 0 0 2 3] Contains Non-Zero Elements = 4


## 3

In [26]:
import numpy as np

In [48]:
a=np.array([[1,2,3,4,0],
            [2,3]],dtype='object')
b=np.array([[1,2,3,4,0],
            [2,3]],dtype='object')
c=np.array([[1,2,3,4,0],
            [2,1]],dtype='object')
d=np.array([[3,2,3,2,3],
            [2,3]],dtype='object')
e=np.array([[65,22,43,64,90],
            [25,31]],dtype='object')
def wiseOP(x,y):
    if ((x==y).all()) and (x.shape==y.shape):
        print("The Two Arrays Are Equal")
    elif ((x==y).all()) or (x.shape==y.shape):
        print("The Two Arrays Are Partially Equal") 

In [49]:
wiseOP(a,b)
wiseOP(b,c)
wiseOP(e,d)

The Two Arrays Are Equal
The Two Arrays Are Partially Equal
The Two Arrays Are Partially Equal


## 4

In [50]:
import numpy as np

In [109]:
a0=np.zeros([10])
a1=np.ones([10])
print(a0)
print(a1)
print(a1*5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5

In [62]:
import numpy as np

In [66]:
a1=np.arange(30,71)
print(a1)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


## 6

In [67]:
import numpy as np

In [68]:
a1=np.eye(3)
print(a1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 7

In [99]:
import numpy as np

In [100]:
a1=np.random.rand()
print(a1)

0.3738205511504903


## 8

In [77]:
import numpy as np

In [97]:
a1=np.random.rand(15)
print((a1))

[0.72361299 0.80277171 0.7662711  0.71535227 0.18624399 0.76999292
 0.45836765 0.10959902 0.60408325 0.71232273 0.08545496 0.2631499
 0.54556541 0.43212249 0.78269757]


## 9

In [110]:
import numpy as np

In [119]:
a1=np.arange(15,56)
print(a1[1:len(a1)-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


## 10

In [123]:
import numpy as np

In [126]:
a1=np.random.randint(0,11,5)
print(a1)

[2 8 9 5 2]


## 11

In [147]:
import numpy as np

In [148]:
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)
    

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


## 12

In [149]:
import numpy as np

In [154]:
x=np.eye(5)*np.arange(1,6)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


## 13

In [155]:
import numpy as np

In [170]:
x=np.ones((4,4))
for i in range(4):
    x[i][i]=0
print(x)

[[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]]


## 14

In [173]:
import numpy as np
import os

In [175]:
x = np.arange(10)
y = np.arange(11, 20)
print("First array is:",x,"Second array is:",y)

np.savez('temp_arra.npz', x=x, y=y)
print("Load arrays from the 'temp_arra.npz' file:")
with np.load('temp_arra.npz') as data:
    x2 = data['x']
    y2 = data['y']
    print(x2)
    print(y2)

First array is: [0 1 2 3 4 5 6 7 8 9] Second array is: [11 12 13 14 15 16 17 18 19]
Load arrays from the 'temp_arra.npz' file:
[0 1 2 3 4 5 6 7 8 9]
[11 12 13 14 15 16 17 18 19]


## 15

In [176]:
import numpy as np  

In [182]:
np.random.seed(10)
print(np.random.rand(40))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665
 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335
 0.00394827 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607
 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362
 0.44183317 0.43401399 0.61776698 0.51313824 0.65039718 0.60103895
 0.8052232  0.52164715 0.90864888 0.31923609 0.09045935 0.30070006
 0.11398436 0.82868133 0.04689632 0.62628715]


## 16

In [183]:
import numpy as np

In [191]:
a1=np.arange(1,51)
a2=[]
a3=[]
print(a1)
x=int(input("Please enter the number you want to compare to:"))
for i in a1:
    if i>x:
        a2.append(i)
    elif i<x:
        a3.append(i)
print("The numbers less than",x,"are",a2)
print("The numbers less than",x,"are",a3)
    

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


Please enter the number you want to compare to: 25


The numbers less than 25 are [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]
The numbers less than 25 are [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
