In [1]:
import json
import numpy as np

In [4]:
with open('data.json') as file:
    data=json.load(file)

In [5]:
data

{'data': [{'label': 'greeting',
   'patterns': ['Hi', 'Hey', 'Is anyone there?', 'Hello', 'Hay'],
   'responses': ['Hello', 'Hi', 'Hi there', 'Hey']},
  {'label': 'about',
   'patterns': ['Who are you?', 'What are you?', 'Who you are?'],
   'responses': ["I'm Zain, your bot assistant",
    "I'm Zain , an Artificial Intelligent bot",
    "I'm Zain , an Amit Artificial Intelligent bot"]},
  {'label': 'name',
   'patterns': ['what is your name?',
    'what should I call you?',
    'whats your name?'],
   'responses': ['You can call me Zain.',
    "I'm Zain!",
    'Just call me as Zain']},
  {'label': 'help',
   'patterns': ['Could you help me?',
    'give me a hand please.',
    'Can you help?',
    'What can you do for me?',
    'I need a support.',
    'I need a help',
    'support me please'],
   'responses': ['Tell me how can assist you',
    'Tell me your problem to assist you',
    'Yes Sure, How can I support you']},
  {'label': 'sad',
   'patterns': ["I'm sad",
    "I'm so sad",
 

In [8]:
training_examples=[]
training_labels=[]
for example in data['data']:
    for pattern in example['patterns']:
        training_examples.append(pattern)
        training_labels.append(example['label'])

In [9]:
training_examples

['Hi',
 'Hey',
 'Is anyone there?',
 'Hello',
 'Hay',
 'Who are you?',
 'What are you?',
 'Who you are?',
 'what is your name?',
 'what should I call you?',
 'whats your name?',
 'Could you help me?',
 'give me a hand please.',
 'Can you help?',
 'What can you do for me?',
 'I need a support.',
 'I need a help',
 'support me please',
 "I'm sad",
 "I'm so sad",
 'I feel bad',
 'I am alone',
 'I have a lot of problems',
 'I am depressed',
 'I need encouragement',
 "I'm so frustrated",
 "I'm so frustrated with myself because I lost confidence",
 'Thanks',
 'Thank you',
 "That's helpful",
 'Thanks for the help',
 'Bye',
 'See you later',
 'Goodbye']

In [10]:
training_labels

['greeting',
 'greeting',
 'greeting',
 'greeting',
 'greeting',
 'about',
 'about',
 'about',
 'name',
 'name',
 'name',
 'help',
 'help',
 'help',
 'help',
 'help',
 'help',
 'help',
 'sad',
 'sad',
 'sad',
 'sad',
 'sad',
 'positive_sen',
 'positive_sen',
 'positive_sen',
 'positive_sen',
 'thanks',
 'thanks',
 'thanks',
 'thanks',
 'goodbye',
 'goodbye',
 'goodbye']

In [11]:
def clean_text(sent):
    result=[]
    for example in sent:
        result.append(example.lower())
    return result

In [12]:
training_examples=clean_text(training_examples)

In [15]:
len(set(training_labels))

8

In [18]:
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
training_labels=le.fit_transform(training_labels)
training_labels=to_categorical(training_labels)
training_labels

array([[0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 

In [48]:
import pickle
pickle.dump(le,open("training_labels_le.pkl","wb"))

In [20]:
from tensorflow.keras.preprocessing.text import one_hot
sequence=[one_hot(example,100,filters='') for example in training_examples]
sequence

[[24],
 [57],
 [91, 90, 22],
 [52],
 [33],
 [76, 36, 60],
 [50, 36, 60],
 [76, 64, 13],
 [50, 91, 75, 30],
 [50, 76, 40, 56, 60],
 [75, 75, 30],
 [97, 64, 81, 61],
 [2, 43, 95, 20, 14],
 [82, 64, 48],
 [50, 82, 64, 72, 27, 61],
 [40, 13, 95, 47],
 [40, 13, 95, 81],
 [5, 43, 39],
 [69, 22],
 [69, 50, 22],
 [40, 55, 16],
 [40, 32, 10],
 [40, 76, 95, 82, 88, 21],
 [40, 32, 11],
 [40, 13, 2],
 [69, 50, 2],
 [69, 50, 2, 1, 37, 60, 40, 12, 18],
 [5],
 [25, 64],
 [91, 1],
 [5, 27, 65, 81],
 [12],
 [91, 64, 90],
 [19]]

In [25]:
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer(num_words=100)
tokenizer.fit_on_texts(training_examples)
sequences=tokenizer.texts_to_sequences(training_examples)
print(sequences)

[[23], [24], [11, 25, 26], [27], [28], [12, 8, 1], [3, 8, 1], [12, 1, 8], [3, 11, 13, 14], [3, 29, 2, 30, 1], [31, 13, 14], [32, 1, 4, 5], [33, 5, 6, 34, 15], [16, 1, 4], [3, 16, 1, 35, 17, 5], [2, 9, 6, 18], [2, 9, 6, 4], [18, 5, 15], [7, 19], [7, 10, 19], [2, 36, 37], [2, 20, 38], [2, 39, 6, 40, 41, 42], [2, 20, 43], [2, 9, 44], [7, 10, 21], [7, 10, 21, 45, 46, 47, 2, 48, 49], [22], [50, 1], [51, 52], [22, 17, 53, 4], [54], [55, 1, 56], [57]]


In [49]:
pickle.dump(tokenizer,open("tokenizer.pkl","wb"))

In [26]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_sequence=pad_sequences(sequences,maxlen=20)
print(padded_sequence)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 23]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 24]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 11 25 26]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 27]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 28]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 12  8  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3  8  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 12  1  8]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3 11 13 14]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  3 29  2 30  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 31 13 14]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 32  1  4  5]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 33  5  6 34 15]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 16  1  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  3 16  1 35 17  5]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  2  9

In [34]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Embedding,Dense,Flatten
model= Sequential()
model.add(Embedding(100,10,input_length=20))
model.add(Flatten())
model.add(Dense(10,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(8,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 20, 10)            1000      
                                                                 
 flatten (Flatten)           (None, 200)               0         
                                                                 
 dense (Dense)               (None, 10)                2010      
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 8)                 88        
                                                                 
Total params: 3,208
Trainable params: 3,208
Non-trainable params: 0
_________________________________________________________________


In [35]:
model.fit(padded_sequence,training_labels,epochs=400)

Epoch 1/400
2/2 [==============================] - 1s 11ms/step - loss: 2.0778 - accuracy: 0.1471
Epoch 2/400
2/2 [==============================] - 0s 4ms/step - loss: 2.0742 - accuracy: 0.2059
Epoch 3/400
2/2 [==============================] - 0s 2ms/step - loss: 2.0720 - accuracy: 0.2059
Epoch 4/400
2/2 [==============================] - 0s 4ms/step - loss: 2.0703 - accuracy: 0.2059
Epoch 5/400
2/2 [==============================] - 0s 3ms/step - loss: 2.0687 - accuracy: 0.2059
Epoch 6/400
2/2 [==============================] - 0s 3ms/step - loss: 2.0675 - accuracy: 0.2059
Epoch 7/400
2/2 [==============================] - 0s 3ms/step - loss: 2.0662 - accuracy: 0.2353
Epoch 8/400
2/2 [==============================] - 0s 3ms/step - loss: 2.0654 - accuracy: 0.2353
Epoch 9/400
2/2 [==============================] - 0s 3ms/step - loss: 2.0644 - accuracy: 0.2353
Epoch 10/400
2/2 [==============================] - 0s 3ms/step - loss: 2.0628 - accuracy: 0.2353
Epoch 11/400
2/2 [==========

In [50]:
pickle.dump(model,open('model.pkl','wb'))

Keras weights file (<HDF5 file "variables.h5" (mode r+)>) saving:
...layers\dense
......vars
.........0
.........1
...layers\dense_1
......vars
.........0
.........1
...layers\dense_2
......vars
.........0
.........1
...layers\embedding
......vars
.........0
...layers\flatten
......vars
...metrics\mean
......vars
.........0
.........1
...metrics\mean_metric_wrapper
......vars
.........0
.........1
...optimizer
......vars
.........0
.........1
.........10
.........11
.........12
.........13
.........14
.........2
.........3
.........4
.........5
.........6
.........7
.........8
.........9
...vars
Keras model archive saving:
File Name                                             Modified             Size
config.json                                    2023-04-17 13:53:02         2356
metadata.json                                  2023-04-17 13:53:02           64
variables.h5                                   2023-04-17 13:53:03        66960


In [41]:
inp='bye'
in_tok=tokenizer.texts_to_sequences([inp])
sent=pad_sequences(in_tok,maxlen=20)

In [42]:
sent

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0, 54]])

In [43]:
model.predict(sent)

1/1 [==============================] - 0s 20ms/step


array([[1.3062103e-03, 9.6866012e-01, 1.5522332e-02, 9.4260753e-07,
        1.9823103e-03, 1.9401415e-03, 1.0401962e-02, 1.8600321e-04]],
      dtype=float32)

In [44]:
y_pred=np.argmax(model.predict(sent))
y_pred

1/1 [==============================] - 0s 18ms/step


1

In [45]:
output=le.inverse_transform(np.array(y_pred).reshape(1))
output

array(['goodbye'], dtype='<U12')

In [46]:
def user_chat():
    while True:
        print('User:',end='')
        inp=input()
        if inp.lower()=='quit':
            break
        in_tok=tokenizer.texts_to_sequences([inp])
        sent=pad_sequences(in_tok,maxlen=20)
        y_pred=np.argmax(model.predict(sent))
        output=le.inverse_transform(np.array(y_pred).reshape(1))
        
        for label in data['data']:
            if label['label']==output:
                print("Chat bot:",np.random.choice(label['responses']))


        

In [ ]:
user_chat()

User: